### PR TITLE
Mason

### PR DESCRIPTION
**Pull request by icefrog-45**
save qr_content to the intent and able to pass to the new activity, create empty afterscan_activity.java

### CODE REVIEW

**Review by shaoherng — COMMENTED** [review]
Great work! The code only has one problem so far and I think it's because you haven't declared afterscan_activity in the AndroidManifest.xml. Other than that, I have restructured the code such that the identification of the type of QR code will run immediately after the QR code content is extracted.

**Comment by shaoherng** [comment]
Sorry for all the changes, I messed up Mason's latest code. I reverted it back and solved all the issues. Now it should be good to be merged. Please test and lmk!

**Review by shaoherng — APPROVED** [review]
Sorry for all the changes, I messed up Mason's latest code. I reverted it back and solved all the issues. Now it should be good to be merged. Please test and lmk!

**Review by banff0 — APPROVED** [review]
Looks good!

**Pull request merged**
