### PR TITLE
Jasper

### PR DESCRIPTION
**Pull request by banff0**
Initial batch of API calls are done, let me know if you encounter any issues when trying to implement them. 
** PLEASE READ THE API DOC WIKI TO UNNDERSTAND HOW TO USE THE CALLS

### CODE REVIEW

**Review by shaoherng — APPROVED** [review]
Looks good to me!

**Comment by icefrog-45** [comment]
I found you commented the testing part. Have you tested all the methods yet?

**Comment by banff0** [comment]
I commented the test part because firebase recognizes that as a different entity, so any attempts to connect to the db from the test environment will not work, but the methods have been tested in the main activity

**Comment by icefrog-45** [comment]
Cannot resolve symbol 'firestore'
Cannot resolve symbol 'FirebaseFirestore'

Not sure if it's because of my firebase settings or other issues 
@shaoherng how is your testing result?

**Comment by shaoherng** [comment]
I don't think I can test it until @banff0 commits have been merged into the master branch right?

**Comment by banff0** [comment]
@icefrog-45 where are those issues popping up? Because I got those, but only before I had the correct dependencies added to my code. Did you sync your gradle cus if not that can also cause that issue. More info would help

**Comment by shaoherng** [comment]
@icefrog-45 I have tested on my local machine and I encountered the same problem as you. However, on my AndroidStudio it provided me the option to resolve it by importing firebase dependency into my Gradle settings. I am not sure why it is the case since @banff0 already imported the dependency. After that, it's all good, at least for the "cannot resolve firebase symbol" issue.

**Comment by banff0** [comment]
@shaoherng android studio might just be giving you that as an option because if you haven't synced your gradle, then AS is not aware of that dependency even though it's actually there. I think the moral of this is just every time we pull code we should also make sure to sync the gradle.

**Pull request merged**
