### PR TITLE
Shao

### PR DESCRIPTION
**Pull request by shaoherng**
- Added the functionality of login via QR code
- Added a line of getIntent() for the CodeScanner_activity.java to identify the previous page that calls the CodeScanner_acitivity.java (Whoever calls this class from their activity should also pass in a value through "intent.putExtra()" when switching activity to CodeScanner_acitivity.java)
-  Modified the code in retrieving the QR code content in CodeScanner_activity.java (It is now structured in a way that caters towards login activity. If you need the QR code content for your activity, please implement your code without affecting the login functionality)

### CODE REVIEW

**Review by banff0 — COMMENTED** [review]
Awesome work Shao everything looks good, and I really like the built in flexibility that this gives us moving forward. The only thing is maybe we could add some kind of alert if the user scans a code that isn't a valid player QR code(like even just a toast, or we could send them back to the sign up screen either one works) just for a slightly better user experience. Otherwise everything runs properly and looks good!

**Comment by shaoherng** [comment]
@banff0 I have addressed the alert you suggested in the latest commit. Please let me know if it's what you have in mind!

**Comment by icefrog-45** [comment]
Firebase connection crushed once. Fixed by adding dependency. No other issues. 
Could you add 

`implementation "io.grpc:grpc-okhttp:1.32.2" `

in the android/app/build.gradle to make sure the firebase work? 

source: https://stackoverflow.com/questions/64668851/why-the-firestore-isnt-working-on-android-studio

**Review by banff0 — APPROVED** [review]
Looks good!

**Comment by icefrog-45** [comment]
Works well. Thanks!

**Pull request merged**
