### PR TITLE
Jasper

### PR DESCRIPTION
**Pull request by banff0**
updated player class to include account for highest/lowest score

### CODE REVIEW

**Comment by shaoherng** [comment]
An error occurred on my machine with the getPlayerInfo method. I think it is called in the LoginActivity.java upon launching the app. Do you think you can look into it? I think it's a problem where the attribute of highestCode in the Player class has a value of null (when it should be an integer)? I haven't tested the addQR method as it got stuck at the getPlayerInfo method.


Screen Shot 2022-03-12 at 10 11 24 PM

**Comment by banff0** [comment]
Hey Shao, sorry about that error, I changed some of the values in the player class so then any older documents in the db had either the wrong type, or were missing some feilds. I've gone through and removed/updated all the documents so they should all have the correct format now. Just double check that your test player hasn't been deleted.

**Review by shaoherng — APPROVED** [review]
Great work Jasper! Everything works well!

**Comment by icefrog-45** [comment]
I checked the branch every things work fine except it turns to old scan page not map page if you click map button on the main page.

**Comment by banff0** [comment]
I never touched any of that code, so not sure what's going wrong there. But the map page was always just a template anyways so I don't think it matters to much where it links to right now

**Pull request merged**
